import Head from "next/head";
import Link from "next/link";

export default function Home({ products }) {
  return (
    <>
      <Head>
        <title>Esight - Task</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="text-gray-600 body-font">
        <div className="container px-5 md:py-18 py-10 mx-auto">
          <div className="flex flex-wrap -m-4 gap-8 md:gap-0">
            {products?.map((item) => (
              <Link className="lg:w-1/4 md:w-1/2 p-6 w-full shadow-md md:shadow-none" key={item.id} href={`/product/${item?.id}`}>
                <div className="block relative h-48 rounded overflow-hidden">
                  <img alt="ecommerce" className="object-contain object-center w-full h-full block" src={item?.image} />
                </div>
                <div className="mt-4">
                  <h3 className="text-gray-500 text-xs tracking-widest title-font mb-1">{item.category}</h3>
                  <h2 className="text-gray-700 title-font text-lg font-normal">{item?.title.length > 35 ? `${item?.title}...` : item?.title}</h2>
                  <p className="mt-1 text-xl font-semibold text-gray-900">${item?.price}</p>
                </div>
              </Link>
            ))}
          </div>
        </div>
      </section>

    </>
  );
}

export async function getServerSideProps() {
  const response = await fetch('https://fakestoreapi.com/products')
  const products = await response.json()
  return {
    props: {
      products
    }
  };
}
